services:
  - type: web
    name: bank-marketing-dashboard
    env: python
    buildCommand: pip install -r requirements-pythonanywhere.txt
    startCommand: gunicorn dashboard.app:server
    plan: free
